export const FETCH_PROFILE_LOADING = "FETCH_PROFILE_LOADING";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAILED = "FETCH_PROFILE_FAILED";

export const FETCH_MOST_RECENT_PROFILES_LOADING =
    "FETCH_MOST_RECENT_PROFILE_LOADING";
export const FETCH_MOST_RECENT_PROFILES_SUCCESS =
    "FETCH_MOST_RECENT_PROFILE_SUCCESS";
export const FETCH_MOST_RECENT_PROFILES_FAILED =
    "FETCH_MOST_RECENT_PROFILE_FAILED";

export const UPDATE_MOST_RECENT_PROFILES_SUCCESS =
    "UPDATE_MOST_RECENT_PROFILES_SUCCESS";

export const FETCH_POSTS_LOADING = "FETCH_POSTS_LOADING";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILED = "FETCH_POSTS_FAILED";

export const ADD_POST_LOADING = "ADD_POST_LOADING";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILED = "ADD_POST_FAILED";

export const FETCH_PHOTOS_LOADING = "FETCH_PHOTOS_LOADING";
export const FETCH_PHOTOS_SUCCESS = "FETCH_PHOTOS_SUCCESS";
export const FETCH_PHOTOS_FAILED = "FETCH_PHOTOS_FAILED";

export const ADD_PHOTO_LOADING = "ADD_PHOTO_LOADING";
export const ADD_PHOTO_SUCCESS = "ADD_PHOTO_SUCCESS";
export const ADD_PHOTO_FAILED = "ADD_PHOTO_FAILED";

export const FETCH_FRIENDS_LOADING = "FETCH_FRIENDS_LOADING";
export const FETCH_FRIENDS_SUCCESS = "FETCH_FRIENDS_SUCCESS";
export const FETCH_FRIENDS_FAILED = "FETCH_FRIENDS_FAILED";

export const ADD_FRIEND_LOADING = "ADD_FRIEND_LOADING";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const ADD_FRIEND_FAILED = "ADD_FRIEND_FAILED";

export const UPDATE_FRIEND_SUCCESS = "UPDATE_FRIEND_SUCCESS";

export const ACCEPT_FRIEND_LOADING = "ACCEPT_FRIEND_LOADING";
export const ACCEPT_FRIEND_SUCCESS = "ACCEPT_FRIEND_SUCCESS";
export const ACCEPT_FRIEND_FAILED = "ACCEPT_FRIEND_FAILED";

export const DELETE_FRIEND_LOADING = "DELETE_FRIEND_LOADING";
export const DELETE_FRIEND_SUCCESS = "DELETE_FRIEND_SUCCESS";
export const DELETE_FRIEND_FAILED = "DELETE_FRIEND_FAILED";
